README.rst
Warn users that this library is in pre-release.
Fixes #27  🦕
=> chore: Add pre-release disclaimer

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/base.py, google/cloud/aiplatform/initializer.py, google/cloud/aiplatform/models.py, google/cloud/aiplatform/utils.py, tests/unit/aiplatform/test_initializer.py, tests/unit/aiplatform/test_models.py, tests/unit/aiplatform/test_utils.py
Includes AI Platform resource noun base class.
Fixes [b/169782649](b/169782649) 🦕
=> Add initial implementation of Model class.

google/cloud/aiplatform/datasets.py, google/cloud/aiplatform/utils.py, tests/unit/aiplatform/test_utils.py
=> feat: fully qualified name util

google/cloud/aiplatform/datasets.py, tests/unit/aiplatform/test_datasets.py
=> bug: remove requirement for import_schema_uri when passing in gcs_source

google/cloud/aiplatform/training_utils.py, tests/unit/aiplatform/test_training_utils.py
adds env var helpers.
partially resolves b/169782082
=> feat: inside script training utils

google/cloud/aiplatform/datasets.py, google/cloud/aiplatform/models.py, google/cloud/aiplatform/training_jobs.py, google/cloud/aiplatform/utils.py, tests/unit/aiplatform/test_utils.py
=> fix: display name length

samples/snippets/create_training_pipeline_custom_job_sample.py, samples/snippets/create_training_pipeline_custom_job_sample_test.py, samples/snippets/deploy_model_custom_trained_model_sample.py, samples/snippets/deploy_model_custom_trained_model_sample_test.py
=> feat: add custom_job samples

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_automl_tabular_training_jobs.py
Renamed AutoMLTablesTrainingJob to AutoMLTabular training job
=> fix: Renamed AutoMLTablesTrainingJob to AutoMLTabular training job

google/cloud/aiplatform/initializer.py, tests/unit/aiplatform/test_initializer.py
Similar to https://github.com/googleapis/python-bigquery/blob/809e4a27b94ba30c10e0c9a7e89576a9de9fda2b/google/cloud/bigquery/magics/magics.py#L596
=> feat: set user_agent

google/cloud/aiplatform/models.py, tests/unit/aiplatform/test_models.py
Added predict schemata support to Model.upload. 
Fixes https://b.corp.google.com/issues/170979552
=> feat: Added predict schemata support to Model.upload

docs/aiplatform.rst, docs/index.rst
=> chore: Support SDK in doc generation

google/cloud/aiplatform/initializer.py, tests/unit/aiplatform/test_initializer.py
Fixes [b/175629206](b/175629206) 🦕
=> fix: unblock builds

README.rst
=> chore: Update README with Experimental verbiage

.sample_configs/param_handlers/create_batch_prediction_job_text_classification_sample.py, .sample_configs/param_handlers/create_batch_prediction_job_text_entity_extraction_sample.py, .sample_configs/param_handlers/create_batch_prediction_job_text_sentiment_analysis_sample.py, samples/snippets/create_batch_prediction_job_text_classification_sample.py, samples/snippets/create_batch_prediction_job_text_entity_extraction_sample.py, samples/snippets/create_batch_prediction_job_text_sentiment_analysis_sample.py
Make these samples consistent with the other create batch prediction job samples.
=> update create batch prediction job samples

google/cloud/aiplatform/initializer.py, google/cloud/aiplatform/jobs.py, google/cloud/aiplatform/utils.py, tests/unit/aiplatform/test_initializer.py, tests/unit/aiplatform/test_utils.py
Results:
```python
import psutil
import pprint
current_process = psutil.Process()
print("connections before creating client: {}".format(len(current_process.connections())))
ds = [aiplatform.Dataset('5836066982746652672') for i in range(5)]
print("connections after creating client: {}".format(len(current_process.connections())))
```
Output:
```
connections before creating client: 12
connections after creating client: 12
```
Fixes [b/174111905](b/174111905) 🦕
=> feat: Implements a wrapped client that instantiates the client at every API invocation

google/cloud/aiplatform/base.py, google/cloud/aiplatform/datasets.py, google/cloud/aiplatform/jobs.py, google/cloud/aiplatform/models.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_lro.py
- Added property and abstract method _getter_method and _resource_noun, implemented method _get_gca_resource to class AiPlatformResourceNoun; 
- Added _resource_noun, _getter_method, to Dataset, Model, Endpoint, subclasses of _Job, _TrainingJob, - Remove/moved (_)get_* and utils.full_resource_name in class constructor to self._get_gca_resource to Dataset, Model, Endpoint, _Job; 
- Updated test
Fixes https://b.corp.google.com/issues/173531466
=> Fix: refactor class constructor for retrieving resource

testing/constraints-3.6.txt
Add constraints file to test lower bounds. These files will not be used until the noxfile is changed in googleapis/synthtool#869
=> test: add constraints file

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_training_jobs.py
Fixes [b/175147058](b/175147058) 🦕
=> feat: Add custom container support

google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_training_jobs.py
fixes: [b/176786861](b/176786861)
=> fix: Support intermediary BQ Table for Custom Training

google/cloud/aiplatform/__init__.py
Fixes #[b/177548340](b/177548340) 🦕
=> chore: add AutoMLImageTrainingJob to aiplatform namespace

google/cloud/aiplatform/base.py, google/cloud/aiplatform/initializer.py, tests/unit/aiplatform/test_end_to_end.py, tests/unit/aiplatform/test_endpoints.py, tests/unit/aiplatform/test_models.py, tests/unit/aiplatform/test_training_jobs.py
fix and follow up on https://github.com/googleapis/python-aiplatform/pull/160
=> fix: default credentials config related test failures

.github/CODEOWNERS
=> chore: Update aiplatform test directory CODEOWNERS

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/datasets/__init__.py, google/cloud/aiplatform/datasets/_datasources.py, google/cloud/aiplatform/datasets/text_dataset.py, tests/unit/aiplatform/test_datasets.py
Fixes #https://b.corp.google.com/issues/177408984
=> feat: add TextDataset class

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_training_jobs.py
- add CustomPythonPackageTrainingJob to aiplatform namespace
- add CustomPythonPackageTrainingJob class
- add CustomPythonPackageTrainingJob test cases
Fixes https://b.corp.google.com/issues/177406034
=> feat: add CustomPythonPackageTrainingJob

google/cloud/aiplatform/schema.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_training_jobs.py
Fixes https://b.corp.google.com/issues/178834223
=> Fix: custom training jobs using managed non tabular dataset requiring annotation_schema_uri 

google/cloud/aiplatform/datasets/dataset.py, google/cloud/aiplatform/jobs.py, google/cloud/aiplatform/models.py, tests/unit/aiplatform/test_jobs.py, tests/unit/aiplatform/test_models.py
https://b.corp.google.com/issues/176178652
=> feat: add async support to batch predict

.sample_configs/param_handlers/upload_model_explain_image_managed_container_sample.py, .sample_configs/param_handlers/upload_model_explain_tabular_managed_container_sample.py, .sample_configs/process_configs.yaml, samples/snippets/conftest.py
Update to sample configurations to make sure changes in https://github.com/googleapis/python-aiplatform/pull/212 will not be overwritten.
=> chore: update sample configs to keep some samples in v1beta1

google/cloud/aiplatform/schema.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_automl_image_training_jobs.py, tests/unit/aiplatform/test_automl_tabular_training_jobs.py
Fixes https://b.corp.google.com/issues/179922436
=> fix: rename schema.training_job.definition tabular_task to automl_tabular

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/schema.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_automl_text_training_jobs.py
This adds the AutoMLTextTrainingJob subclass:
Fixes #https://b.corp.google.com/issues/179106243
=> feat: Added AutoMLTextTrainingJob and tests

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/constants.py, google/cloud/aiplatform/schema.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_automl_video_training_jobs.py
Fixes https://b.corp.google.com/issues/179127059
=> feat: add automl video training class

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/datasets/__init__.py, google/cloud/aiplatform/datasets/image_dataset.py, google/cloud/aiplatform/datasets/tabular_dataset.py, google/cloud/aiplatform/datasets/text_dataset.py, google/cloud/aiplatform/datasets/video_dataset.py, tests/unit/aiplatform/test_datasets.py
Fixes #<https://b.corp.google.com/issues/179127058> 🦕
=> feat: VideoDataset class

noxfile.py, tests/system/aiplatform/test_dataset.py
Fixes part of [b/178500935](http://b/178500935) and unblocks [cl/362114575](http://cl/362114575) 🦕
=> chore: Modify integration tests to support VPC-SC environment

google/cloud/aiplatform/__init__.py
=> chore: add init to documentation

google/cloud/aiplatform/models.py
=> refactor: remove BatchPredictionJob forward reference

google/cloud/aiplatform/base.py, tests/unit/aiplatform/test_models.py
Fixes [b/182290998](http://b/182290998) 🦕
=> feature: Use gca_resource as repr and provide informative repr if asynchronous

samples/snippets/create_custom_job_sample_test.py, samples/snippets/create_hyperparameter_tuning_job_python_package_sample_test.py, samples/snippets/create_hyperparameter_tuning_job_sample_test.py, samples/snippets/create_training_pipeline_custom_training_managed_dataset_sample_test.py
Update GCR images and GCS artifacts to be accessible by sample testing CI.
Fixes b/184550505🦕
=> chore: Repair GAPIC sample test failures from permission issue

samples/snippets/create_custom_job_sample_test.py, samples/snippets/create_hyperparameter_tuning_job_python_package_sample_test.py, samples/snippets/create_hyperparameter_tuning_job_sample_test.py, samples/snippets/create_training_pipeline_custom_training_managed_dataset_sample_test.py
=> chore: merge main into dev

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/initializer.py, google/cloud/aiplatform/metadata/metadata.py, tests/unit/aiplatform/test_initializer.py
Feat: Delete log_param/log_metric methods. Also update init method to not take a run as the input. 
Also corrected a couple typo.
=> Remove stuff

README.rst
=> chore: remove Experimental verbiage

google/cloud/aiplatform/models.py, google/cloud/aiplatform/training_jobs.py
=> chore: remove TPU references from docstrings

google/cloud/aiplatform/constants.py, tests/unit/aiplatform/test_initializer.py
[Source of truth](http://shortn/_0dyRkrvrda)
Fixes [b/186123342](http://b/186123342) 🦕
=> fix: Add all supported uCAIP GA regions

samples/model-builder/conftest.py, samples/model-builder/create_and_import_dataset_video_sample.py, samples/model-builder/create_and_import_dataset_video_sample_test.py, samples/model-builder/import_data_video_action_recognition_sample.py, samples/model-builder/import_data_video_action_recognition_sample_test.py, samples/model-builder/import_data_video_classification_sample.py, samples/model-builder/import_data_video_classification_sample_test.py, samples/model-builder/import_data_video_object_tracking_sample.py, samples/model-builder/import_data_video_object_tracking_sample_test.py
=> Feat: add mbsdk video dataset samples

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/datasets/__init__.py, google/cloud/aiplatform/datasets/_datasources.py, google/cloud/aiplatform/datasets/time_series_dataset.py, google/cloud/aiplatform/schema.py, google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
=> chore: merge dev into dev-test

google/cloud/aiplatform/compat/__init__.py, google/cloud/aiplatform/compat/services/__init__.py, google/cloud/aiplatform/compat/types/__init__.py, google/cloud/aiplatform/tensorboard/__init__.py, google/cloud/aiplatform/tensorboard/uploader.py, google/cloud/aiplatform/tensorboard/uploader_main.py, google/cloud/aiplatform/utils.py, setup.py, tests/unit/aiplatform/test_uploader.py
Adding the Tensorboard.gcp uploader into python-aiplatform
=> feat: adding TB.gcp uploader to python-aiplatform

samples/snippets/create_batch_prediction_job_tabular_forecasting_sample_test.py, samples/snippets/create_batch_prediction_job_text_classification_sample_test.py, samples/snippets/create_batch_prediction_job_text_entity_extraction_sample_test.py, samples/snippets/create_batch_prediction_job_text_sentiment_analysis_sample_test.py, samples/snippets/create_batch_prediction_job_video_action_recognition_sample_test.py, samples/snippets/create_batch_prediction_job_video_classification_sample_test.py, samples/snippets/create_batch_prediction_job_video_object_tracking_sample_test.py, samples/snippets/create_dataset_image_sample_test.py, samples/snippets/create_dataset_tabular_gcs_sample_test.py, samples/snippets/create_dataset_video_sample_test.py, samples/snippets/create_hyperparameter_tuning_job_python_package_sample_test.py, samples/snippets/create_training_pipeline_custom_job_sample_test.py, samples/snippets/create_training_pipeline_custom_training_managed_dataset_sample_test.py, samples/snippets/create_training_pipeline_image_classification_sample_test.py, samples/snippets/create_training_pipeline_image_object_detection_sample_test.py, samples/snippets/create_training_pipeline_tabular_classification_sample_test.py, samples/snippets/create_training_pipeline_tabular_forecasting_sample_test.py, samples/snippets/create_training_pipeline_text_sentiment_analysis_sample_test.py, samples/snippets/create_training_pipeline_video_action_recognition_sample_test.py, samples/snippets/create_training_pipeline_video_classification_sample_test.py, samples/snippets/deploy_model_custom_trained_model_sample_test.py, samples/snippets/export_model_tabular_classification_sample_test.py, samples/snippets/export_model_video_action_recognition_sample_test.py, samples/snippets/import_data_text_entity_extraction_sample_test.py, samples/snippets/import_data_video_action_recognition_sample_test.py, samples/snippets/import_data_video_classification_sample_test.py, samples/snippets/upload_model_explain_image_managed_container_sample_test.py, samples/snippets/upload_model_explain_tabular_managed_container_sample_test.py
Fixes #438 #426 #437 #413 #395   🦕
=> test: disabled tests to reduce the cost & resolve quota issues

google/cloud/aiplatform/pipeline_jobs.py, tests/unit/aiplatform/test_pipeline_jobs.py
=> fix: log pipeline completion and raise pipeline failures

google/cloud/aiplatform/experimental/vertex_model/base.py, google/cloud/aiplatform/experimental/vertex_model/utils/source_utils.py, tests/unit/aiplatform/test_cloud_training_job.py
=> feat: Accommodate multiple parameters in children of VertexModel

setup.py
Reapplying #499 to remove the extra dependencies introduced by merge conflict in https://github.com/googleapis/python-aiplatform/commit/f6f9a97bb178d9859b8d43166a43792d88e57710#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L32-R36
=> fix: re-remove extra TB dependencies introduced due to merge conflict

google/cloud/aiplatform/experimental/vertex_model/serializers/dataloaders.py, google/cloud/aiplatform/experimental/vertex_model/serializers/model.py, google/cloud/aiplatform/experimental/vertex_model/serializers/pandas.py, google/cloud/aiplatform/experimental/vertex_model/serializers/serializer_utils.py, tests/unit/aiplatform/test_cloud_training_job.py, tests/unit/aiplatform/test_serialization.py
- Added serialization/deserialization for DataLoaders with both remote and local sources
- Added serialization/deserialization for model objects
- Added tests for both forms of serialization
=> feat: Serialization and deserialization of PyTorch DataLoader objects

owlbot.py, samples/model-builder/noxfile.py, samples/snippets/noxfile.py
Generate python samples templates in owlbot.py
=> chore: generate python samples templates in owlbot.py

google/cloud/aiplatform/experimental/vertex_model/README.rst
Created readme prior to bug bash.
=> chore: Create README.rst

.github/.OwlBot.lock.yaml, CONTRIBUTING.rst, owlbot.py
chore: removing owlbot directives for conversion to main
=> chore: removing owlbot directives for conversion to main

README.rst
=> docs: Add code sample for Pipelines

.github/CODEOWNERS
Fixes [b/198660774](http://b/198660774) 🦕
=> chore: Update Vertex SDK code owners

tests/system/aiplatform/e2e_base.py
=> chore: Add explicit project name to E2E create_bucket

owlbot.py
This change is required for googleapis/synthtool#1201
=> chore: exclude codeowners template

tests/unit/aiplatform/test_models.py
=> fix: Fixed model uploading unittests failing on python 3.6

samples/snippets/prediction_service/predict_image_object_detection_sample.py
=> chore(samples): update uri in object detection yaml

README.rst, tests/system/aiplatform/test_model_upload.py
=> docs: Update references to containers and notebook samples.

samples/model-builder/create_training_pipeline_image_classification_sample.py, samples/model-builder/create_training_pipeline_image_classification_sample_test.py, samples/model-builder/test_constants.py
add model_type for automl training to support edge export example
=> samples: add model_type for create_training_pipeline_image_classification_sample

samples/model-builder/create_training_pipeline_tabular_classification_sample.py, samples/model-builder/create_training_pipeline_tabular_classification_sample_test.py
=> fix: issues/192254729

google/cloud/aiplatform/explain/lit.py
Fixes [#211814939](http://b/211814939)
=> fix: use open_in_new_tab in the render method.

google/cloud/aiplatform/utils/source_utils.py, tests/unit/aiplatform/test_end_to_end.py, tests/unit/aiplatform/test_training_jobs.py
Allow _TrainingScriptPythonPackager to support a folder in addition to a single script.
Related to: https://b.corp.google.com/issues/204787988
=> feat: _TrainingScriptPythonPackager to support folders

tests/system/aiplatform/test_model_upload.py
Fixed bug in integration test introduced by https://github.com/googleapis/python-aiplatform/pull/952
=> fix: Fixed integration test for model.upload

google/cloud/aiplatform/prediction/__init__.py, google/cloud/aiplatform/prediction/handler.py, google/cloud/aiplatform/prediction/handler_utils.py, google/cloud/aiplatform/prediction/model_server.py, google/cloud/aiplatform/prediction/predictor.py, google/cloud/aiplatform/prediction/serializer.py, pytest.ini, setup.py, tests/unit/aiplatform/test_prediction.py
prediction folder for custom prediction routine and added extra
requirements for prediction.
=> feat: Initialized predictor, serializer, and model server in the 

setup.py
=> fix(deps): allow google-cloud-storage < 3.0.0dev

google/cloud/aiplatform/prediction/handler_utils.py, tests/unit/aiplatform/test_prediction.py
=> fix: Removed the parameter from the content-type/accept in handler.

google/cloud/aiplatform/docker_utils/errors.py, google/cloud/aiplatform/docker_utils/local_util.py, google/cloud/aiplatform/prediction/local_model.py, google/cloud/aiplatform/utils/prediction_utils.py, tests/unit/aiplatform/test_docker_utils.py, tests/unit/aiplatform/test_prediction.py, tests/unit/aiplatform/test_utils.py
=> feat: Added copying and pushing image functionalities to local model.

tests/system/aiplatform/test_featurestore.py
=> fix: loosen assertions for system test featurestore

samples/notebooks/prediction/SDK_Custom_Predict.ipynb
=> feat: Add CPR M2 sample notebook

samples/notebooks/prediction/SDK_Custom_Predict.ipynb
=> fix: formatting fixes to SDK_Custom_Predict.ipynb

google/cloud/aiplatform/prediction/sklearn/__init__.py, google/cloud/aiplatform/prediction/sklearn/predictor.py
=> feat: Add default SklearnPredictor

setup.py, testing/constraints-3.6.txt
fix(deps): require proto-plus>=1.15.0
=> fix(deps): require google-api-core>=1.31.5, >=2.3.2

google/cloud/aiplatform/prediction/sklearn/__init__.py, google/cloud/aiplatform/prediction/sklearn/predictor.py, samples/notebooks/prediction/SDK_Custom_Predict.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
=> feat: Add a notebook sample for CPR SDK integration modified from Custom

google/cloud/aiplatform/prediction/sklearn/predictor.py
=> fix: Restructure SklearnPredictor

samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb
=> feat: Add M4 preprocess sample

samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
=> fix: Updated naming to be unique across samples.

samples/notebooks/prediction/SDK_Custom_Predict.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb
=> fix: Add dependencies/env caveat to prediction notebooks

google/cloud/aiplatform/prediction/sklearn/predictor.py, tests/system/aiplatform/test_featurestore.py, tests/system/aiplatform/test_model_upload.py
=> fix: Cherry-picked two commits from main branch to get the system tests green.

google/cloud/aiplatform/prediction/handler.py, google/cloud/aiplatform/prediction/sklearn/predictor.py, tests/unit/aiplatform/test_prediction.py
=> fix: Fixed accept header in handler.

google/cloud/aiplatform/prediction/handler_utils.py, tests/unit/aiplatform/test_prediction.py
=> fix: Fixed regular expression for content-type and accept in header

google/cloud/aiplatform/prediction/handler_utils.py, samples/notebooks/prediction/SDK_Custom_Predict.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb, tests/unit/aiplatform/test_prediction.py
=> fix: Fixed github links, iris links, credential comments and wording.

google/cloud/aiplatform/prediction/local_endpoint.py, tests/unit/aiplatform/test_prediction.py
=> fix: Hide health check logs on initial start.

samples/notebooks/prediction/SDK_Custom_Predict.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb, samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb
=> fix: Use gcloud to set up SA for local run.

tests/system/__init__.py, tests/system/aiplatform/__init__.py
=> ci: resolve import error when running system tests

setup.py
Resolves #1118 #1115 #1113 #1111 #1109
=> chore: Add upper bound for werkzeug

google/cloud/aiplatform/models.py
=> fix: system tests failure from test_upload_and_deploy_xgboost_model

google/cloud/aiplatform/docker_utils/run.py, tests/unit/aiplatform/test_docker_utils.py
See https://cloud.google.com/ai-platform/prediction/docs/reference/rest/v1/projects.models.versions#containerspec.
=> fix: Replace env var references in given env, command and arg.

README.rst, google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/model_evaluation/__init__.py, google/cloud/aiplatform/model_evaluation/model_evaluation.py, google/cloud/aiplatform/models.py, tests/unit/aiplatform/test_model_evaluation.py, tests/unit/aiplatform/test_models.py
Added initial support for the ModelEvaluation gapic client:
* `ModelEvaluation` class defined in `model_evaluation/`
* Exposed `ModelEvaluation` class in `models.py`
* Added related tests
Fixes b/224573576 🦕
=> feat: add ModelEvaluation support

google/cloud/aiplatform/training_jobs.py, tests/unit/aiplatform/test_training_jobs.py
Change default value for `create_request_timeout` from `False` to `None` and add test for when `create_request_timeout` isn't explicitly set.
Fixes b/229868042 🦕
=> fix: change default for create_request_timeout arg to None

tests/unit/aiplatform/test_custom_job.py, tests/unit/aiplatform/test_datasets.py, tests/unit/aiplatform/test_endpoints.py, tests/unit/aiplatform/test_featurestores.py, tests/unit/aiplatform/test_jobs.py, tests/unit/aiplatform/test_models.py, tests/unit/aiplatform/test_pipeline_jobs.py, tests/unit/aiplatform/test_tensorboard.py, tests/unit/aiplatform/test_training_jobs.py
Added tests to ensure the default value of the timeout arg is set correctly. 
Fixes b/229967745 🦕
=> chore: add tests for timeout arg not being explicitly set

.kokoro/continuous/continuous.cfg, owlbot.py
Adds network constant to be injected for system tests.
=> tests: Added VPC network constant

tests/system/aiplatform/test_dataset.py
Cleaned up the dataset system tests per the feedback in https://github.com/googleapis/python-aiplatform/pull/1209.
=> chore: cleanup Dataset system tests

google/cloud/aiplatform/prediction/local_endpoint.py, google/cloud/aiplatform/prediction/local_model.py, setup.py, tests/system/aiplatform/test_prediction_cpr.py, tests/unit/aiplatform/test_prediction.py
Let's discuss whether or not to check in this..
=> chore: Add a new way to deploy to local endpoint for CPR to interactively do local prediction.

google/cloud/aiplatform/prediction/xgboost/__init__.py, google/cloud/aiplatform/prediction/xgboost/predictor.py
Adds basic XgboostPredictor. Will add support for other file names later.
=> feature: Add OOB XgboostPredictor

google/cloud/aiplatform/models.py, tests/unit/aiplatform/test_uploader.py
Fix import in `test_uploader` to be consistent with imports across SDK.
=> chore: update import statement in test_uploader

google/cloud/aiplatform/docker_utils/build.py, google/cloud/aiplatform/docker_utils/run.py, google/cloud/aiplatform/docker_utils/utils.py, google/cloud/aiplatform/prediction/README.md, google/cloud/aiplatform/prediction/handler.py, google/cloud/aiplatform/prediction/handler_utils.py, google/cloud/aiplatform/prediction/local_model.py, google/cloud/aiplatform/prediction/model_server.py, google/cloud/aiplatform/prediction/predictor.py, google/cloud/aiplatform/prediction/serializer.py, google/cloud/aiplatform/prediction/sklearn/predictor.py, google/cloud/aiplatform/prediction/xgboost/predictor.py, setup.py
- Fixed shlex_quote.
- Fixed return types.
- Added starlette import for type hinting.
- Fixed docstrings.
- Changed cpr branch to main branch and showed it is preview now.
=> fix: Fixed comments from the merging PR.

google/cloud/aiplatform/metadata/experiment_resources.py, google/cloud/aiplatform/metadata/experiment_run_resource.py, google/cloud/aiplatform/metadata/metadata.py, tests/unit/aiplatform/test_metadata.py
=> chore: reference pypi package in exception instead of github repo name

google/cloud/aiplatform/metadata/artifact.py, tests/unit/aiplatform/test_metadata_resources.py
Guidance from the Metadata team in this comment: https://github.com/googleapis/python-aiplatform/pull/1430/files#r899141877
=> chore: update default state for artifacts to LIVE

tests/system/aiplatform/test_e2e_metadata_schema.py
=> chore: fix metadata schema integration tests

google/cloud/aiplatform/constants/prediction.py, google/cloud/aiplatform/prediction/sklearn/predictor.py, google/cloud/aiplatform/prediction/xgboost/predictor.py
Add loading of more filenames to sklearn and xgboost OOB predictors.
=> feature: Update OOB predictors to accept more model filenames.

owlbot.py
=> chore: pin python3.6 revert for OwlBot

samples/model-builder/noxfile.py, tests/unit/aiplatform/test_metadata_schema.py
This change includes an update to make Metadata tests pass in our internal infra. 
Also includes formatting update to nox file. 
=> chore: Update metadata tests to use google_auth_mock.

google/cloud/aiplatform/utils/prediction_utils.py, tests/system/aiplatform/test_prediction_cpr.py, tests/unit/aiplatform/test_utils.py
=> chore: Fixed GCS bug and unit tests.

.github/CODEOWNERS
Adding the code owner group for Vertex AI Metadata SDK team.
=> chore: Add code owners for Vertex Metadata SDK

google/cloud/aiplatform/prediction/predictor.py
=> chore: Update docstring for Predictor to be clearer

google/cloud/aiplatform/__init__.py, google/cloud/aiplatform/metadata/context.py, google/cloud/aiplatform/metadata/experiment_resources.py, google/cloud/aiplatform/metadata/experiment_run_resource.py, google/cloud/aiplatform/metadata/metadata.py, google/cloud/aiplatform/metadata/schema/base_context.py, google/cloud/aiplatform/metadata/schema/system/context_schema.py, google/cloud/aiplatform/pipeline_jobs.py, tests/unit/aiplatform/test_metadata_resources.py, tests/unit/aiplatform/test_metadata_schema.py, tests/unit/aiplatform/test_utils.py
=> feat: Change the Metadata SDK _Context class to an external class

tests/system/aiplatform/test_dataset.py
Update the dataset url for `test_get_new_dataset_and_import` to use a bucket in the same project as the test.
Fixes https://github.com/googleapis/python-aiplatform/issues/1484 🦕
=> chore: change dataset url in dataset import system test

google/cloud/aiplatform/pipeline_jobs.py
=> fix: Pass the PipelineJob credentials to `create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist`

google/cloud/aiplatform/prediction/local_model.py, google/cloud/aiplatform/prediction/model_server.py, tests/unit/aiplatform/test_prediction.py
=> chore: Append users' src dir name to sys.path while model server starts for CPR.

tests/system/aiplatform/test_model_monitoring.py
Fixes #<240633310, 240929827> 🦕
=> chore: fix resource deletion issues with model monitoring system tests

samples/model-builder/experiment_tracking/get_execution_input_artifacts_sample.py, samples/model-builder/experiment_tracking/get_execution_input_artifacts_sample_test.py, samples/model-builder/experiment_tracking/get_execution_output_artifacts_sample.py, samples/model-builder/experiment_tracking/get_execution_output_artifacts_sample_test.py
=> Feat: Add samples for get execution input and output artifacts

setup.py, testing/constraints-3.7.txt
fix(deps): require proto-plus >= 1.22.0
=> fix(deps): allow protobuf < 5.0.0

tests/system/aiplatform/test_model_monitoring.py
=> chore: fix incorrect syntax in model monitoring system tests

tests/system/aiplatform/test_dataset.py
Fixes https://github.com/googleapis/python-aiplatform/issues/1596
=> chore: shorten image dataset display name in system test

samples/model-builder/conftest.py, samples/model-builder/create_training_pipeline_forecasting_sample.py, samples/model-builder/create_training_pipeline_forecasting_seq2seq_sample.py, samples/model-builder/create_training_pipeline_forecasting_seq2seq_sample_test.py, samples/model-builder/create_training_pipeline_tabular_regression_sample.py
Adds seq2seq sample for forecasting.
Fixes b/241717026
=> docs(samples): Added seq2seq sample

tests/system/aiplatform/test_model_monitoring.py
=> chore: refactor model monitoring system test to make it more efficient

tests/system/aiplatform/e2e_base.py, tests/system/aiplatform/test_e2e_tabular.py
We should run the AutoML training job to completion to catch any issues.
We'll wait until after the next release to merge this.
Reverts googleapis/python-aiplatform#1627
=> Revert "chore: e2e tabular system test improvement"

google/cloud/aiplatform/metadata/experiment_run_resource.py, tests/unit/aiplatform/test_metadata.py, tests/unit/aiplatform/test_pipeline_jobs.py
Fixes [b/246541115](http://b/246541115)
=> chore: Replace collections.Iterable reference to collections.abc.Iterable for Python 3.10

google/cloud/aiplatform/pipeline_jobs.py
Changed `enable_simple_view` param in PipelineJob.list() from Optional to `False`.
=> chore: change enable_simple_view default to False

.github/CODEOWNERS
=> chore: update codeowners for pipeline job client

google/cloud/aiplatform/constants/prediction.py, google/cloud/aiplatform/prediction/handler.py, google/cloud/aiplatform/prediction/model_server.py, tests/unit/aiplatform/test_prediction.py
=> chore: Add headers for CPR model server errors.

samples/model-builder/experiment_tracking/create_experiment_sample.py, samples/model-builder/experiment_tracking/create_experiment_sample_test.py
Fixes [b\251048133](b\251048133) 🦕
=> docs: fix create experiment sample

.github/.OwlBot.lock.yaml, owlbot.py
This reverts commit 895ff8d324bb951706bbcd94b1414f5b5e181265.
=> chore(revert): revert "use the latest python post processor image"

.kokoro/release.sh
Note: do not merge your PR from GitHub. Adding the "ready to pull" label is the final step in the review process.
After approvals, the changes in your PR will be committed to the `main` branch and this PR will be closed.
=> chore: prevent pip to look for dependencies at the installation time

.kokoro/release.sh, .kokoro/release/common.cfg
PiperOrigin-RevId: 675755826
Note: do not merge your PR from GitHub. Adding the "ready to pull" label is the final step in the review process.
After approvals, the changes in your PR will be committed to the `main` branch and this PR will be closed.
=> chore: Update release script
