google/cloud/aiplatform_v1beta1/services/job_service/client.py
google/cloud/aiplatform_v1beta1/services/prediction_service/client.py
synth.metadata
synth.py
tests/unit/aiplatform_v1beta1/test_job_service.py
tests/unit/aiplatform_v1beta1/test_prediction_service.py

Related issues:
https://github.com/googleapis/gapic-generator-python/issues/413
https://github.com/googleapis/gapic-generator-python/issues/414

bugfix: fix prediction service and unit tests

---

google/cloud/aiplatform/__init__.py
google/cloud/aiplatform/gapic/__init__.py

*DO NOT MERGE* until confirmed about the approach.
Current user code (which will be broken after this change):
```
from google.cloud import aiplatform
dataset = aiplatform.Dataset(...)
```
Expected user code after this change:
```
from google.cloud import aiplatform
dataset = aiplatform.gapic.Dataset(...)
```

GAPIC namespace

---

google/cloud/aiplatform/__init__.py
google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/schema.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_datasets.py
tests/unit/aiplatform/test_lro.py
tests/unit/aiplatform/test_training_jobs.py

Adds CustomTrainingJob Class.
The current implementation splits the constructing of the CustomTrainingJob and running of the Job. Note that no Custom Training service resource is created when the object is constructed. It is created at the `run` call. Which can lead to issues if the correct args were not passed in during construction. This mainly is an issue for model serving args as we require the model serving environment definitions at construction time, which should make sense because it's tightly coupled to the script provided at construction time. An alternative is to move this to the run call.
An additional alternative is to add all constructor and run args to the constructor. And only have the model accessible through the get_model API:
```python
job = …
```

feat: Add Custom Training by Python Script

---

samples/snippets/get_custom_job_sample.py
samples/snippets/get_custom_job_sample_test.py
samples/snippets/get_hyperparameter_tuning_job_sample.py
samples/snippets/get_hyperparameter_tuning_job_sample_test.py

add get_custom_job and get_hyperparameter_tuning_job samples

feat: add get_custom_job and get_hyperparameter_tuning_job samples

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Adds support for chief-worker distributed training to custom training. If replica_count > 1 the remainder as provisioned as workers
The _DistributedTrainingSpec can also support more custom provisioning. We will have a follow up PR after we consider how we want to expose more custom provisioning on the API surface.
Note: If library upgrades to 3.7 we should switch the Spec classes to dataclass.
Fixes [b/172369809](b/172369809) 🦕

feat: add support for distributed custom training

---

google/cloud/aiplatform/training_jobs.py

There is reusable code in `CustomTrainingJob`, specifically in the `init` and `run` methods. Other training jobs such as `AutoMLTablesTrainingJob` can use it as well.
The code mainly has to do with creating and running a training pipeline.
The leftover code in `CustomTrainingJob` will thus only be related to custom training and not generic pipeline code.
In preparation for: https://b.corp.google.com/issues/172282518
~~1. In the `TrainingJob.run` method, `training_fraction_split`, `validation_fraction_split`, `test_fraction_split: float` are all only needed when the `dataset` parameter is also provided. I've grouped this together into `DatasetWithSplits`. I'd want to replace the `CustomTrainingJob.run` parameters with this as well. What do you all think?~~
~~2. Should we put `TrainingJob` …

refactor: Pull out reusable code in CustomTrainingJob to use in other training jobs

---

google/cloud/aiplatform/__init__.py
google/cloud/aiplatform/schema.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_tables_training_jobs.py

Added support for AutoMLTablesTraining.
Fixes https://b.corp.google.com/issues/172282518
Depends on https://github.com/googleapis/python-aiplatform/pull/49
Could possibly add more client-side validation, but currently deferring validation to the backend services pending more discussion.

feat: Added AutoMLTablesTrainingJob and tests

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_tables_training_jobs.py

- Uses the job display name if is not passed in.
- Added unit test
Fixes https://b.corp.google.com/issues/174146765

AutoMLTablesTrainingJob: Make model_display_name optional and use the job's display_name if not passed in.

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

This adds predefined splits to custom training jobs.
Fixes https://b.corp.google.com/issues/172366411
Unit-tested by checking the expected Gapic input data config is created.

feat: Added predefined splits to custom training jobs

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

According to the yaml file, pre-defined splits can only be used with a tabular dataset. A ValueError is now raised if that's not the case.
fixes: https://b.corp.google.com/issues/174495379

fix: Added client check for a tabular dataset when using pre-defined splits

---

synth.py

This PR updates the synth.py file to use the `GAPICBazel` generator. It builds the `aiplatform-v1beta1-py` rule, which includes the build rules for the enhanced types.

chore: updates synth.py to use Bazel generator

---

samples/snippets/explain_tabular_sample.py
samples/snippets/explain_tabular_sample_test.py
samples/snippets/upload_model_explain_image_managed_container_sample.py
samples/snippets/upload_model_explain_image_managed_container_sample_test.py
samples/snippets/upload_model_explain_tabular_managed_container_sample.py
samples/snippets/upload_model_explain_tabular_managed_container_sample_test.py

feat: xai samples

---

google/cloud/aiplatform/models.py

According to backend engineers, these fields are unused.
Fixes https://b.corp.google.com/issues/170979552

fix: Added to comments for predict_schemata fields.

---

setup.py

This makes the mb-release package show up as version `0.4.0a1`, and allows the user to revert to the public package with `pip install google-cloud-aiplatform==0.3.1`.

chore: alpha

---

google/cloud/aiplatform/__init__.py
google/cloud/aiplatform/schema/__init__.py
google/cloud/aiplatform/v1beta1/schema/__init__.py
google/cloud/aiplatform/v1beta1/schema/predict/__init__.py
google/cloud/aiplatform/v1beta1/schema/predict/instance/__init__.py
google/cloud/aiplatform/v1beta1/schema/predict/params/__init__.py
google/cloud/aiplatform/v1beta1/schema/predict/prediction/__init__.py
google/cloud/aiplatform/v1beta1/schema/trainingjob/__init__.py
google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/__init__.py
samples/snippets/create_training_pipeline_image_classification_sample.py
samples/snippets/predict_image_classification_sample.py

Allow access to the schema modules with the following imports:
```
from google.cloud.aiplatform.schema import trainingjob
from google.cloud.aiplatform.schema import predict
```
Each schema module has its own submodules such as `trainingjob.definition` and `predict.params`.

feat: add schema namespace

---

google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_models.py
tests/unit/aiplatform/test_training_jobs.py

Added optional args to `CustomTrainingJob.init`:
```
model_serving_container_command: Optional[Sequence[str]] = None,
model_serving_container_args: Optional[Sequence[str]] = None,
model_serving_container_environment_variables: Optional[Dict[str, str]] = None,
model_serving_container_ports: Optional[Sequence[int]] = None,
model_description: Optional[str] = None,
model_instance_schema_uri: Optional[str] = None,
model_parameters_schema_uri: Optional[str] = None,
model_prediction_schema_uri: Optional[str] = None,
```
Fixes https://b.corp.google.com/issues/172365796

feat: Added optional model args for custom training

---

.sample_configs/process_configs.yaml
samples/snippets/create_training_pipeline_image_classification_sample.py
samples/snippets/create_training_pipeline_image_object_detection_sample.py
samples/snippets/create_training_pipeline_text_classification_sample.py
samples/snippets/create_training_pipeline_text_entity_extraction_sample.py
samples/snippets/create_training_pipeline_text_sentiment_analysis_sample.py
samples/snippets/create_training_pipeline_video_action_recognition_sample.py
samples/snippets/create_training_pipeline_video_classification_sample.py
samples/snippets/create_training_pipeline_video_object_tracking_sample.py

Update with samples generated with the schema types.

feat: update create_training_pipeline samples

---

.sample_configs/param_handlers/predict_image_classification_sample.py
.sample_configs/param_handlers/predict_image_object_detection_sample.py
samples/snippets/predict_image_classification_sample.py
samples/snippets/predict_image_object_detection_sample.py

Fixes https://github.com/googleapis/python-aiplatform/issues/147.

fix: predict image samples params

---

.github/CODEOWNERS

Adding the Github teams of respective AI Platform libraries to their owners

chore: update CODEOWNERS with GAPIC and SDK dev teams

---

.sample_configs/param_handlers/create_batch_prediction_job_tabular_forecasting_sample.py
samples/snippets/create_batch_prediction_job_tabular_forecasting_sample.py
samples/snippets/create_batch_prediction_job_tabular_forecasting_sample_test.py

Add batch prediction sample for tabular forecasting.
Fixes https://b.corp.google.com/issues/176736455

feat: Added batch prediction tabular forecasting sample

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/utils.py

Fixes https://b.corp.google.com/issues/176166878

fix: suppress no project id warning

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_image_training_jobs.py

The training task key "multiLabel" was incorrectly named "modelLabel" which results in failed training job run.
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "TrainingJob.inputs does not match job definition: com.google.protobuf.InvalidProtocolBufferException: Cannot find field: modelLabel in message google.cloud.aiplatform.master.schema.trainingjob.definition.AutoMlImageClassificationInputs."
debug_error_string = "{"created":"@1610450635.815653353","description":"Error received from peer ipv4:74.125.195.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"TrainingJob.inputs does not match job definition: com.google.protobuf.InvalidProtocolBufferException: Cannot find field: modelLabel in …
```

Fixed incorrect key for AutoMLTrainingJob

---

google/cloud/aiplatform/training_jobs.py

Fixed an issue causing AutoMLImageTrainingJob to fail for the "object_detection" use case.
```
google.api_core.exceptions.InvalidArgument: 400 TrainingJob.inputs does not match job definition: com.google.protobuf.InvalidProtocolBufferException: Cannot find field: multiLabel in message google.cloud.aiplatform.master.schema.trainingjob.definition.AutoMlImageObjectDetectionInputs.
```

fix: Fixed bug causing training failure for object detection

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Fixes [b/178188165](b/178188165) 🦕

Fix: pass bq_destination to input data config when using training script

---

setup.py

`mock` is only needed to run the tests https://github.com/googleapis/python-aiplatform/blob/8c0932f3f4d0e1ac40e55b1f0b2ce67c1873dee6/noxfile.py#L75-L77 and `libcst` is not needed by this library.
Fixes #183

fix(deps): remove optional dependencies

---

google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
google/cloud/aiplatform/utils.py

Addition of `accelerator_type` and `accelerator_count` to `Endpoint.deploy()` and `Model.deploy()` methods. Also added a util method to validate the `accelerator_type` against the GAPIC Enum.
Manually tested that deploying with GPUs work. Does not affect existing tests.
Fixes [b/179069467](http://b/179069467) 🦕

feat: Add accelerator options to Model/Endpoint deploy()

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_jobs.py
tests/unit/aiplatform/test_lro.py
tests/unit/aiplatform/test_training_jobs.py

- Add `_delete_method` abstract property to `AiPlatformResourceNoun` class, requiring a resource noun to define it's delete method in GAPIC (i.e. `Dataset` would set this property to `delete_dataset`)
- Add abstract property `_cancel_method` to `_Job` class to force children to define it's cancel method (i.e. `BatchPredictionJob` would set `cancel_batch_prediction_job`
- Add high-level `delete()` method to `AiPlatformResourceNounWithFutureManager` that calls subclass deletion method
- Shifted the `optional_sync` decorator higher in `base.py` to be referenced by `delete()` for async capability
- Removed `Dataset.delete()` and `Model.delete()` but left their tests; they now test the high-level delete method
- Add `_TrainingJob.cancel()` and `_Job.cancel()` along with unit tests
Fixes …

feat: Add SDK-wide delete method, cancel methods to Job and TrainingJob

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

This allows users to retrieve an existing CustomTrainingJob using the resource name.
The `get` function will always block as it is a short function.
The `get_model` is now async, so downstream functions can use the future that was created at this stage.
Fixes https://b.corp.google.com/issues/174771897
I've tested this against the below potential use cases.
```
job = aiplatform.CustomTrainingJob(...)
model = job.run(ds, replica_count=1, model_display_name="abalone-model")
Session stops...
job = aiplatform.CustomTrainingJob.get(
resource_name="resource_name"
)
job.state # Should be pending/success/failure
```
```
job = aiplatform.CustomTrainingJob(...)
model = job.run(ds, replica_count=1, model_display_name="abalone-model")
Session stops...
job = aiplatform.CustomTrainingJob.get( …
```

feat: Added CustomTrainingJob.get

---

.sample_configs/param_handlers/export_model_sample.py
samples/snippets/export_model_sample.py
samples/snippets/export_model_sample_test.py

Fixes: https://github.com/googleapis/python-aiplatform/issues/196

fix: fix update export model sample, and add sample test

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Lifted `get` function to `_TrainingJob` so that all subclasses can use this function to get an existing TrainingJob.
Fixes #https://b.corp.google.com/issues/180746020

feat: Made get function available to all training jobs

---

samples/snippets/predict_custom_trained_model_sample_test.py
samples/snippets/predict_image_object_detection_sample_test.py
samples/snippets/predict_tabular_classification_sample_test.py

proto-plus==1.14.2 caused some predict samples to print different outputs, removing the unwanted tags such as 'string_value`, `number_value`, etc. when protobuf.Value is wrapped in a `dict` call.

fix: fix predict sample tests for proto-plus==1.14.2

---

.github/sync-repo-settings.yaml

Merge commits are used for syncing `dev` and `master`.

chore: allow merge commits

---

samples/snippets/create_data_labeling_job_active_learning_sample_test.py
samples/snippets/create_data_labeling_job_image_segmentation_sample_test.py
samples/snippets/create_data_labeling_job_images_sample_test.py
samples/snippets/create_data_labeling_job_sample_test.py
samples/snippets/create_data_labeling_job_specialist_pool_sample_test.py
samples/snippets/create_data_labeling_job_video_sample_test.py

The job state is flaky.  Instead of capturing multiple job states in the sample tests and their teardown code, skip these tests for now.

fix: skip create data labeling job sample tests

---

google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/datasets/image_dataset.py
google/cloud/aiplatform/datasets/tabular_dataset.py
google/cloud/aiplatform/datasets/text_dataset.py
google/cloud/aiplatform/datasets/video_dataset.py
google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_image_training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_automl_text_training_jobs.py
tests/unit/aiplatform/test_automl_video_training_jobs.py
tests/unit/aiplatform/test_datasets.py
tests/unit/aiplatform/test_end_to_end.py
tests/unit/aiplatform/test_endpoints.py
tests/unit/aiplatform/test_models.py
tests/unit/aiplatform/test_training_jobs.py

The encryption key can be passed into aiplatform.init which will be applied to all applicable resources:
```
aiplatform.init(
project=_TEST_PROJECT,
encryption_spec_key_name=_TEST_DEFAULT_ENCRYPTION_KEY_NAME,
)
```
Alternatively, it can be passed directly into the resource itself on creation. This will override the aiplatform default.
1. Added CMEK support to:
2. Added tests:
Currently Unused:
Fixes [b/178500930](https://b.corp.google.com/issues/178500930)

feat: Added encryption_spec_key_name to all relevant resources

---

google/cloud/aiplatform/training_jobs.py

In lines (line 768-778) in training_jobs.py:
```
setup_cmd = self._SETUP_PY_SOURCE_DISTRIBUTION_CMD.format(
python_executable=_get_python_executable()
).split()
p = subprocess.Popen(
args=setup_cmd,
cwd=trainer_root_path,
stdout=subprocess.PIPE,
stderr=subprocess.PIPE,
)
```
If your python executable path has spaces in it, you get an exception:
`FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/GoogleDrive/Shared'`
which is the part of your executable path before the first space.
This fixes avoids combining the executable and args together, which fixes the problem.

fix: Fixed exception when the python executable path has a space in it

---

google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/models.py
tests/unit/aiplatform/test_initializer.py
tests/unit/aiplatform/test_models.py

- Make `artifact_uri` optional in `Model.upload()` to allow for custom containers that contain model artifacts & server
- Remove reference to specific prediction endpoint (`*-prediction-aiplatform.googleapis.com`) - [link to commit](https://github.com/googleapis/python-aiplatform/commit/bbd92185237673d28504e227e2b254d002b041a9)
- Update relevant tests
Fixes [b/184049758](http://b/184049758), [b/180036930](http://b/180036930) 🦕

feat: Add Custom Container Prediction support, move to single API endpoint

---

.github/sync-repo-settings.yaml

Temporarily removing hard requirement to have all sample tests passing to merge to `master` until after AI Platform (Unified) GA.

chore: Remove hard sample test requirement

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_datasets.py
tests/unit/aiplatform/test_training_jobs.py

_unit tests:_
Fixes <[b/180923329](https://b.corp.google.com/issues/180923329)>

Feat: parse project location when passed full resource name to get apis

---

google/cloud/aiplatform/base.py
tests/unit/aiplatform/test_datasets.py

fix: fix list failing without order_by and local sorting

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Fixes #<[b/184155454](https://b.corp.google.com/issues/184155454)> 🦕

fix: remove model_display_name requirement for training jobs

---

google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_endpoints.py
tests/unit/aiplatform/test_models.py
tests/unit/aiplatform/test_training_jobs.py

- Add `service_account` parameter to `run()` method of the three Custom Training classes
- Add `service_account` parameter to `deploy()` in `Endpoint` and `Model`
- Update tests to get coverage in each class that was modified
Fixes [b/183951295](http://b/183951295) 🦕

feat: Add service account support to Custom Training and Model deployment

---

google/cloud/aiplatform/jobs.py

Quick update to pass project to clients used in `iter_outputs()`
Manually tested `iter_outputs()` on batch prediction job that used BQ and GCS as outputs.
Fixes [b/182902518](http://b/182902518) 🦕

fix: Pass project to BQ and GCS clients

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/datasets/_datasources.py
google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/datasets/image_dataset.py
google/cloud/aiplatform/datasets/tabular_dataset.py
google/cloud/aiplatform/datasets/text_dataset.py
google/cloud/aiplatform/datasets/video_dataset.py
google/cloud/aiplatform/helpers/value_converter.py
google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
google/cloud/aiplatform/training_utils.py
google/cloud/aiplatform/utils.py

Fixing docstring formatting for aiplatform.(Fixes #358)

fix(aiplatform): Fix doc formatting

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/models.py
tests/unit/aiplatform/test_models.py

- Add `Model.export_model()`
- Transform and expose `Model.supported_export_formats`
- Override `__getattr__` in `AiPlatformResourceNoun` to fall back on the `_gca_resource` if a particular attribute has not been exposed by the SDK
- Add 5 unit tests to test `export_model()`
Fixes [b/186130284](http://b/186130284) 🦕

feat: Add export model

---

samples/model-builder/conftest.py
samples/model-builder/create_and_import_dataset_video_sample_test.py
samples/model-builder/explain_tabular_sample.py
samples/model-builder/explain_tabular_sample_test.py
samples/model-builder/import_data_video_classification_sample_test.py
samples/model-builder/test_constants.py
samples/model-builder/upload_model_explain_tabular_managed_container_sample.py
samples/model-builder/upload_model_explain_tabular_managed_container_sample_test.py

Waiting for merge of https://github.com/googleapis/python-aiplatform/pull/337

feat: Added explain tabular samples

---

google/cloud/aiplatform/datasets/_datasources.py
google/cloud/aiplatform/datasets/tabular_dataset.py
google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/training_jobs.py
google/cloud/aiplatform/utils.py
tests/system/aiplatform/test_dataset.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_datasets.py

```
from google.cloud.aiplatform import training_jobs
ds = aiplatform.TabularDataset.create(display_name="sample-gsod", bq_source="bq://bigquery-public-data.samples.gsod")
job = training_jobs.AutoMLTabularTrainingJob(
display_name="tabular_regression_job_test",
optimization_objective="minimize-rmse",
optimization_prediction_type="regression",
column_transformations=None,
optimization_objective_recall_value=None,
optimization_objective_precision_value=None,
)
model_from_job = job.run(
dataset=ds,
target_column="mean_temp",
model_display_name="tabular_model",
sync=True,
)
```
fixes: https://b.corp.google.com/issues/181042526

feat: Added default AutoMLTabularTrainingJob column transformations

---

setup.py
testing/constraints-3.6.txt

This PR (https://github.com/googleapis/python-aiplatform/pull/357) introduced a mock that uses google.cloud.storage.blob.Blob.download_as_bytes.
This method was introduced in 1.32.0.

fix: Bump google-cloud-storage min version to 1.32.0

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Fixes #<[b/186513106](https://b.corp.google.com/issues/186513106)> 🦕

feat: expose env var in cust training class run func args

---

google/cloud/aiplatform/tensorboard/uploader_main.py

Just learned today that the new hostname is up and running. Updating the uploader to make use of it.

fix: updating TB webserver hostname

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Exposes the `network` parameter in `CustomTrainingJob.run()` and subclasses to allow user to peer Job to a GCE network.
Fixes [b/186368472](http://b/186368472) 🦕

feat: Add VPC Peering support to CustomTrainingJob classes

---

setup.py
testing/constraints-3.6.txt

Add packaging requirement. packaging.version
is used for a version comparison in transports/base.py and is needed after the upgrade to gapic-generator-python 0.46.3

fix(deps): add packaging requirement

---

setup.py

six 1.16 is causing neverending pip lookups

fix: rollback six to 1.15

---

google/cloud/aiplatform/jobs.py
tests/unit/aiplatform/test_custom_job.py
tests/unit/aiplatform/test_hyperparameter_tuning_job.py

feat: add tensorboard support to custom job and hyperparameter tuning job

---

.github/CODEOWNERS
.repo-metadata.json
README.rst
google/cloud/aiplatform/base.py
google/cloud/aiplatform/datasets/_datasources.py
google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/datasets/image_dataset.py
google/cloud/aiplatform/datasets/tabular_dataset.py
google/cloud/aiplatform/datasets/text_dataset.py
google/cloud/aiplatform/datasets/time_series_dataset.py
google/cloud/aiplatform/datasets/video_dataset.py
google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/metadata/artifact.py
google/cloud/aiplatform/metadata/context.py
google/cloud/aiplatform/metadata/execution.py
google/cloud/aiplatform/metadata/metadata_store.py
google/cloud/aiplatform/metadata/resource.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/schema.py
google/cloud/aiplatform/training_jobs.py
google/cloud/aiplatform/utils/__init__.py
google/cloud/aiplatform/utils/worker_spec_utils.py
setup.py
tests/unit/aiplatform/test_custom_job.py
tests/unit/aiplatform/test_hyperparameter_tuning_job.py

- This is branched off of https://github.com/googleapis/python-aiplatform/pull/404. Hold merging until that is in.
- Docstrings and documentation contain renames.
- Class names for Vertex SDK have been renamed.

chore: Replace AI Platform naming with Vertex AI

---

google/cloud/aiplatform/tensorboard/uploader_main.py

- Plumbing the flags from uploader_main to __main__ such that "tb-gcp-uploader --help" will show flag definitions
- defining new flags for api and web server uri, to allow for communicating with non-prod APIs

fix: tb-gcp-uploader to show flags in "--help" correctly, and new flags for api uri overriding

---

google/cloud/aiplatform/base.py
tests/unit/aiplatform/test_datasets.py

fix: use resource name location when passed full resource name

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py

feat: support additional_experiments for AutoML Tables and AutoML Forecasting

---

google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/metadata/metadata_store.py
tests/unit/aiplatform/test_metadata.py

fix: Enable MetadataStore to use credentials when aiplatfrom.init passed experiment and credentials. 

---

samples/model-builder/create_endpoint_sample.py

Remove the `endpoint.uri` attribute from `create_endpoint_sample.py`.
Resolves Buganizer [issue](http://b/189844848)
Fixes #189844848🦕

fix: Remove URI attribute from Endpoint sample

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

fix: check if training_task_metadata is populated before logging backingCustomJob

---

setup.py

Fixes b/191305567.
Vertex notebooks, and (I suppose) the majority of users have "tensorflow" installed, instead of "tensorflow-cpu", which doesn't play nice with "tensorflow" and forces to pin on weird specific dependency versions.
Tried on notebooks with TF 2.3 and 2.5, as well as brand-new conda envs. All seemed working fine.

fix: making the uploader depend on tensorflow-proper

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/models.py
tests/unit/aiplatform/test_endpoints.py

Overrides `VertexAiResourceNounWithFutureManager._construct_sdk_resource_from_gapic` with `Endpoint._construct_sdk_resource_from_gapic`.
Subclass method initializes the Prediction service client, allowing users to call `predict()` / `explain()` on an `Endpoint` returned by a call to `list()`
Fixes [b/192002630](http://b/192002630) 🦕

fix: Set prediction client when listing Endpoints

---

google/cloud/aiplatform/datasets/tabular_dataset.py
tests/unit/aiplatform/test_datasets.py

Fixes '`ds.column_names` doesn't contain nested fields in BigQuery table' issue.
According to the product team, only "leaf node" fields should be passed to AutoML tabular.
Added unit test for it.
Fixes b/191864144 🦕

fix: Handle nested fields from BigQuery source when getting default column_names

---

google/cloud/aiplatform/pipeline_jobs.py

Corresponding change in KFP SDK: https://github.com/kubeflow/pipelines/pull/6052/files

feat: enable_caching in PipelineJob to compile time settings

---

samples/snippets/noxfile_config.py

cl/356265286 removed samples checks for python 3.6 and 3.8 for `python-aiplatform`. The Yoshi Core python team would like to standardize samples checks among all python googleapis repos. This PR will ensure that when the required samples checks are re-enabled, the samples checks for python 3.6 and 3.8 will be skipped.

chore: skip samples checks for python 3.6/8/9

---

google/cloud/aiplatform/jobs.py
tests/unit/aiplatform/test_custom_job.py
tests/unit/aiplatform/test_hyperparameter_tuning_job.py

feat: expose base_output_dir for custom job

---

google/cloud/aiplatform/datasets/tabular_dataset.py

The `end` parameter of the [blob.download_as_bytes](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.download_as_bytes) function is inclusive, not exclusive. 
Fixes https://github.com/googleapis/python-aiplatform/issues/589
> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.
Fixes #589

fix: Fixed the column name corruption bug in TabularDataset.column_names

---

google/cloud/aiplatform/tensorboard/uploader.py
tests/unit/aiplatform/test_uploader.py

Exacted out common logic from the 3 BatchedRequestSenders into a base class. 
This will facilitate optimizations down the road.
As nice side effects this brings up the uploader's test coverage due to fewer lines of code, and allows blob references to be batched instead of sent one at a time.
unit test passed. Tried uploading all 3 types of data. Working well.

refactor: Extract out common logic from Tensorboard BatchedRequestSender into a base class.

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/metadata/resource.py
tests/system/aiplatform/test_dataset.py

This method allows getting the resource metadata as a standard Python dictionary.
Without this method, any user who would want to do this would have to access private fields.

feat: Added the VertexAiResourceNoun.to_dict() method

---

google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/datasets/image_dataset.py
google/cloud/aiplatform/datasets/tabular_dataset.py
google/cloud/aiplatform/datasets/text_dataset.py
google/cloud/aiplatform/datasets/time_series_dataset.py
google/cloud/aiplatform/datasets/video_dataset.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/pipeline_jobs.py
google/cloud/aiplatform/tensorboard/tensorboard.py
google/cloud/aiplatform/training_jobs.py
google/cloud/aiplatform/utils/__init__.py
tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
tests/unit/aiplatform/test_automl_image_training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_automl_text_training_jobs.py
tests/unit/aiplatform/test_automl_video_training_jobs.py
tests/unit/aiplatform/test_custom_job.py
tests/unit/aiplatform/test_datasets.py
tests/unit/aiplatform/test_endpoints.py
tests/unit/aiplatform/test_hyperparameter_tuning_job.py
tests/unit/aiplatform/test_models.py
tests/unit/aiplatform/test_training_jobs.py
tests/unit/aiplatform/test_utils.py

Fixes #595, <b/191789899> 🦕
- Add support for labels in resources creation: 
- datasets (`create`)
- ImageDataset / TabularDataset / TextDataset / TimeSeriesDataset / VideoDataset
- tensorboard 
- `Tensorboard.create`
- jobs
- `BatchPredictionJob.create`
- `CustomJob.__init__`
- `HyperparameterTuningJob.__init__`
- models
- `Endpoint.create`
- `Model.upload` / `Model.batch_predict`
- training_jobs (`__init__` for training labels, `run` for model labels)
- CustomTrainingJob / CustomContainerTrainingJob / CustomPythonPackageTrainingJob 
- AutoMLTabularTrainingJob / AutoMLForecastingTrainingJob / AutoMLImageTrainingJob / AutoMLVideoTrainingJob / …

Feat: add labels to all resource creation apis

---

google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/models.py
tests/unit/aiplatform/test_jobs.py

Fixes [b/191995461](http://b/191995461) and [b/186764629](http://b/186764629)  🦕

fix: Update BatchPredictionJob.iter_outputs() and BQ docstrings

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
tests/unit/aiplatform/test_automl_image_training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_automl_text_training_jobs.py
tests/unit/aiplatform/test_automl_video_training_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Changes to training splits:
- Defers default splits to the server instead of setting in client
- Raises error when multiple split types passed
- Adds filter splits (b/172365904) to image, text and video
- Adds timestamp split (b/172368070) to tabular
- Added tests for all split types
Future:
- next PR will change forecasting training jobs to extend tabular; therefore, adding timestamp and predefined split to forecasting
Continued from: https://github.com/googleapis/python-aiplatform/pull/549

feat: add filter and timestamp splits 

---

google/cloud/aiplatform/utils/tensorboard_utils.py
tests/unit/aiplatform/test_utils.py

feat: add util functions to get URLs for Vertex Tensorboard web app.

---

README.rst
google/cloud/aiplatform/explain/metadata/metadata_builder.py
google/cloud/aiplatform/explain/metadata/tf/v1/saved_model_metadata_builder.py
google/cloud/aiplatform/explain/metadata/tf/v2/saved_model_metadata_builder.py
tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf1_test.py
tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf2_test.py

Add a explanationMetadata Object for re-use.

feat: add explanation metadata `get_metadata_protobuf` for reuse

---

google/cloud/aiplatform/explain/metadata/tf/v1/saved_model_metadata_builder.py
google/cloud/aiplatform/explain/metadata/tf/v2/saved_model_metadata_builder.py
tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf1_test.py
tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf2_test.py

Fixes [b/199751138](http://b/199751138) 🦕

fix: XAI Metadata compatibility with Model.upload

---

README.rst

Currently `sync=sync` is confusing for users for the type of sync to pass in.

chore: Use `True` for PipelineJob for clearer documentation

---

google/cloud/aiplatform/tensorboard/uploader.py
google/cloud/aiplatform/tensorboard/uploader_main.py
tests/unit/aiplatform/test_uploader.py

b/190431961.
go/tb-uploader-speedup
- The BatchedRequestSenders were sending requests for each run - now changed to batch for all runs in the experiment.
- Generalizing the existing _TimeSeriesResourceManager to _OnePlatformResourceManager such that it manages caching for runs as well, in addition to time series.
- Updating the scalar and blob request sizes to 128kb so that it's in sync with the OSS TB (https://github.com/tensorflow/tensorboard/blob/29cfcec9d15c47d1bf54b15df24e65bc38c188e6/tensorboard/uploader/server_info.py#L51)
- Changing uploader_main to call uploader.start_uploading() only, which inherently handles whether the upload was one_shot or not.
Ran the new code for scalar, tensor, blob data. Looks fine to me.

feat: Updating the Tensorboard uploader to use the new batch write API so it runs more efficiently

---

google/cloud/aiplatform/pipeline_jobs.py
tests/unit/aiplatform/test_pipeline_jobs.py

Previously, `create_time` is used to identify whether a job has been created. Now since we have `job_id` fixed, we could leave `name` out for output only and identify whether a job has been created using `name`.

fix(PipelineJob): use name as output only field

---

google/cloud/aiplatform/jobs.py
tests/unit/aiplatform/test_jobs.py

It is possible that the user specify a different project than the current project as the BQ output destination for batch prediction job.

fix: use the project id from BQ dataset instead of the default project id

---

samples/model-builder/create_and_import_dataset_image_sample.py

* Includes imports within code sample
* Provides example of `src_uris` parameter

docs: Improved image dataset creation sample

---

google/cloud/aiplatform/tensorboard/uploader_main.py
tests/unit/aiplatform/test_uploader_main.py

The training backend doesn't store custom job display names, so the uploader would need to fetch the job display name on its own.
This allows experiments to be more recognizable in the Cloud Console experiment list UI.
b/203591169

feat: default to custom job display name if experiment name looks like a custom job ID

---

google/cloud/aiplatform/compat/__init__.py
google/cloud/aiplatform/tensorboard/plugins/tf_profiler/profile_uploader.py
google/cloud/aiplatform/tensorboard/uploader.py
google/cloud/aiplatform/tensorboard/uploader_utils.py
tests/unit/aiplatform/test_uploader.py

feat: updating Tensorboard related code to use v1

---

samples/model-builder/create_and_import_dataset_tabular_bigquery_sample.py
samples/model-builder/create_and_import_dataset_tabular_bigquery_sample_test.py

docs: Update name of BQ source parameter in samples

---

.sample_configs/process_configs.yaml
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/models.py
samples/snippets/prediction_service/predict_image_classification_sample.py
samples/snippets/prediction_service/predict_image_object_detection_sample.py
samples/snippets/prediction_service/predict_tabular_classification_sample.py
samples/snippets/prediction_service/predict_tabular_regression_sample.py
samples/snippets/prediction_service/predict_text_classification_single_label_sample.py
samples/snippets/prediction_service/predict_text_entity_extraction_sample.py
samples/snippets/prediction_service/predict_text_sentiment_analysis_sample.py

Fixes https://github.com/googleapis/python-aiplatform/issues/474, https://github.com/googleapis/python-aiplatform/issues/467, [b/196053040](http://b/196053040) 🦕

fix: Minor docstring and snippet fixes

---

samples/model-builder/create_training_pipeline_image_classification_sample.py
samples/model-builder/create_training_pipeline_image_classification_sample_test.py

fix: add param for multi-label per user's feedback

---

samples/model-builder/predict_tabular_classification_sample.py
samples/model-builder/predict_tabular_classification_sample_test.py
samples/model-builder/predict_tabular_regression_sample.py
samples/model-builder/predict_tabular_regression_sample_test.py

fix: add clarity to parameters per user feedback

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/datasets/_datasources.py
google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/explain/metadata/tf/v1/saved_model_metadata_builder.py
google/cloud/aiplatform/explain/metadata/tf/v2/saved_model_metadata_builder.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/metadata/metadata.py
google/cloud/aiplatform/metadata/resource.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/training_jobs.py
google/cloud/aiplatform/utils/featurestore_utils.py
google/cloud/aiplatform/utils/tensorboard_utils.py

Generated docs were not properly parsing the `Raises` section of docstrings, when no colon was provided after the name of the exception class. This PR updates docstrings to address this issue.

docs: Updated docstrings with exception error classes

---

samples/model-builder/deploy_model_with_automatic_resources_sample.py
samples/model-builder/deploy_model_with_dedicated_resources_sample.py

fix: add clarity to param model_name

---

google/cloud/aiplatform/initializer.py
google/cloud/aiplatform/training_utils/cloud_profiler/plugins/tensorflow/tensorboard_api.py
tests/unit/aiplatform/test_initializer.py

Fixes [b/210643836](b/210643836) 🦕 and failing unit tests.

fix: add support for API base path overriding

---

google/cloud/aiplatform/models.py
tests/unit/aiplatform/test_endpoints.py

- Add informative error when undeploying a model with traffic from an Endpoint with multiple deployed models, without providing a new traffic split.
- Improve accuracy of docstring for `Endpoint.undeploy()`
- Add tests to cover CUJs
Fixes [b/198290421](http://b/198290421) 🦕

fix: Improve handling of undeploying model without redistributing remaining traffic

---

setup.py

for b/210986314, where users of the latest TF will get downgraded one because of the lower version upper bound of the tb uploader.
OSS TensorBoard team discourages eliminating the upper bound. I.e., >= 2.5.0 was frowned upon.
Tried installing the uploader and uploading. Worked fine.

chore: upgrading tb uploader tf dependency

---

google/cloud/aiplatform/explain/lit.py
setup.py
tests/unit/aiplatform/test_explain_lit.py

Add automatic addition of feature attribution for TensorFlow 2 models in the LIT integration on Vertex Notebooks. Detects for Vertex Notebooks by looking for the same environment variable to check for Vertex Notebooks as the LIT library does.
Fixes b/210943910 🦕
go/local-explanations-lit-xai-notebook

feat: Add XAI SDK integration to TensorFlow models with LIT integration

---

google/cloud/aiplatform/models.py
tests/system/aiplatform/test_model_upload.py
tests/unit/aiplatform/test_models.py

Added ability to update `display_name`, `description` and `labels`.
Fixes https://b.corp.google.com/issues/213921337
```
models = Model.list()
my_model = models[0]
print(f"eTag: {my_model._gca_resource.etag}")
print(f"Current display_name: {my_model.display_name}")
my_model = my_model.update(display_name=my_model.display_name + "_new")
print(f"Current display_name: {my_model.display_name}")
print(f"eTag: {my_model._gca_resource.etag}")
my_model = Model(my_model.resource_name)  # Fetch model from server
print(f"eTag after fetch: {my_model._gca_resource.etag}")
print(f"Current description: {my_model.description}")
my_model = my_model.update(description=my_model.description + "_new")
print(f"Current description: {my_model.description}")
print(f"eTag: {my_model._gca_resource.etag}")
my_model …
```

feat: Added `aiplatform.Model.update`  method

---

google/cloud/aiplatform/models.py

Goal: make it easier for the calling functions to ask for the latest framework version.
It turns out that the current approach complicates calling the upload_* functions, because there is no values of the *_version parameter that mean "latest version". This leads to the need to have different code paths depending on whether the user has given an explicit version value.
Example of the problem:
```python
def my_import_xgboost_model(
model_path: str,
xgboost_version: Optional[str] = None,
):
if xgboost_version:
aiplatfor.Model.upload_xgboost_model(model_path=model_path, xgboost_version=xgboost_version)
else:
aiplatfor.Model.upload_xgboost_model(model_path=model_path)
```
With this small change, the call is simplified:
```python
def my_import_xgboost_model(
model_path: str,
xgboost_version: …
```

chore: Made it easier to use the latest framework version when calling Model.upload_*

---

google/cloud/aiplatform/featurestore/entity_type.py
google/cloud/aiplatform/featurestore/feature.py
google/cloud/aiplatform/featurestore/featurestore.py
setup.py
tests/system/aiplatform/test_featurestore.py
tests/unit/aiplatform/test_featurestores.py

feat: enable feature store batch serve to Pandas DataFrame; fix: read instances uri for batch serve

---

tests/system/aiplatform/e2e_base.py
tests/system/aiplatform/test_e2e_tabular.py
tests/system/aiplatform/test_model_upload.py

PyTest version 7.0 was released on Feb 4. 
```
Calling a fixture function directly, as opposed to request them in a test function, is deprecated.
```
This deprecation is affecting the system tests.

fix: rename teardown fixture

---

google/cloud/aiplatform/training_jobs.py
tests/system/aiplatform/test_e2e_tabular.py
tests/unit/aiplatform/test_training_jobs.py

Added scheduling to CustomTrainingJob and CustomContainerTrainingJob according to established API from CustomJob.

feat: Added scheduling to CustomTrainingJob, CustomPythonPackageTrainingJob, CustomContainerTrainingJob

---

setup.py

The empty kwarg `scripts` was introduced in https://github.com/googleapis/python-aiplatform/pull/96.
Towards #1003 🦕

fix: remove empty scripts kwarg in setup.py

---

tests/system/aiplatform/test_model_upload.py

fix: update system test_model_upload to use BUILD_SPECIFIC_GCP_PROJECT

---

google/cloud/aiplatform/constants/base.py
tests/unit/aiplatform/test_utils.py

Add Vertex Tables Q1 regions in the SUPPORTED_REGIONS set to enable the SDK. The implementation of these regions is complete and the change is required for E2E tests.

feat: Add support for Vertex Tables Q1 regions

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/pipeline_jobs.py
google/cloud/aiplatform/training_jobs.py
tests/system/aiplatform/test_e2e_tabular.py
tests/unit/aiplatform/test_jobs.py
tests/unit/aiplatform/test_pipeline_jobs.py
tests/unit/aiplatform/test_training_jobs.py

Added a done method via a `DoneMixin` class to check the status of long running jobs (returns True or False based on job state):
* Implemented by `PipelineJob`, `_Job`, and `_TrainingJob`
* Added system tests in `aiplatform/tests/system/aiplatform/test_e2e_tabular.py`
* Added pipeline job tests in `tests/unit/aiplatform/test_pipeline_jobs.py`
* Still need to add unit tests in `test_jobs` and `test_training_jobs`
Fixes b/215396514

feat: Add done method for pipeline, training, and batch prediction jobs

---

google/cloud/aiplatform/matching_engine/matching_engine_index_endpoint.py
google/cloud/aiplatform/models.py

fix: add self.wait() in operations after optional_sync supported resource creation

---

google/cloud/aiplatform/models.py
tests/system/aiplatform/test_e2e_tabular.py
tests/unit/aiplatform/test_end_to_end.py
tests/unit/aiplatform/test_endpoints.py

Fixes # [b/224990641](b/224990641) 🦕

feat: Add timeout arguments to Endpoint.predict and Endpoint.explain

---

google/cloud/aiplatform/training_jobs.py

Updates documentation for Vertex Forecasting run function to specify column types for columns with time dependency properties.

docs: Include time dependency in documentation for weight, time, and target columns.

---

google/cloud/aiplatform/training_jobs.py

Updated https://github.com/googleapis/python-aiplatform/pull/1104/files to replace "service account" with "local credentials" in the docstrings for `column_specs` and `column_transformations`.

chore: update docstring for column_specs and column_transformations to specify local credentials

---

google/cloud/aiplatform/docker_utils/run.py
tests/unit/aiplatform/test_docker_utils.py

as https://cloud.google.com/vertex-ai/docs/predictions/custom-container-requirements#server.

fix: Set serving_container_command to entrypoint instead of command to match our requirements

---

google/cloud/aiplatform/models.py
tests/unit/aiplatform/test_endpoints.py

feat: Add endpoind_id arg to Endpoint#create

---

google/cloud/aiplatform/featurestore/featurestore.py
tests/system/aiplatform/test_featurestore.py

feat: allow creating featurestore without online node

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_forecasting_training_jobs.py

feat: Allow users to specify timestamp split for vertex forecasting

---

.kokoro/continuous/common.cfg
.kokoro/continuous/continuous.cfg
owlbot.py

After testing, it seems that common.cfg should work better.

tests: Added VPC network constants to common file instead of continuous

---

google/cloud/aiplatform/compat/__init__.py
google/cloud/aiplatform/compat/types/__init__.py
google/cloud/aiplatform/models.py
google/cloud/aiplatform/pipeline_jobs.py
tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
tests/unit/aiplatform/test_automl_image_training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_automl_text_training_jobs.py
tests/unit/aiplatform/test_automl_video_training_jobs.py
tests/unit/aiplatform/test_custom_job.py
tests/unit/aiplatform/test_datasets.py
tests/unit/aiplatform/test_end_to_end.py
tests/unit/aiplatform/test_endpoints.py
tests/unit/aiplatform/test_explain_lit.py
tests/unit/aiplatform/test_featurestores.py
tests/unit/aiplatform/test_hyperparameter_tuning_job.py
tests/unit/aiplatform/test_initializer.py
tests/unit/aiplatform/test_jobs.py
tests/unit/aiplatform/test_matching_engine_index.py
tests/unit/aiplatform/test_matching_engine_index_endpoint.py
tests/unit/aiplatform/test_metadata_store.py
tests/unit/aiplatform/test_model_evaluation.py
tests/unit/aiplatform/test_models.py
tests/unit/aiplatform/test_pipeline_jobs.py
tests/unit/aiplatform/test_tensorboard.py
tests/unit/aiplatform/test_training_jobs.py
tests/unit/aiplatform/test_uploader.py
tests/unit/aiplatform/test_uploader_main.py

chore: Remove _v1 specific references in favor of compat types and services

---

tests/system/aiplatform/test_dataset.py
tests/system/aiplatform/test_featurestore.py

Two fixes for failing system tests:
* Added `tear_down_resources` fixture to `TestFeaturestore` class so that created resources are deleted
* Re-added `import_request_timeout` to `test_get_new_dataset_and_import` since it's intermittently failing

chore: update system tests to tear down resources

---

tests/system/aiplatform/test_e2e_tabular.py
tests/system/aiplatform/test_metadata.py
tests/system/aiplatform/test_model_upload.py
tests/system/aiplatform/test_tensorboard.py

Added the `tear_down_resources` fixture to system test classes: e2e_tabular, metadata, model_upload, and tensorboard.

chore: add tear_down_resources fixture to individual system test classes

---

google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_forecasting_training_jobs.py

Add holiday regions for Vertex Forecasting.
---
Fixes b/232964228 🦕

feat: add holiday regions for vertex forecasting

---

tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf1_test.py
tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf2_test.py
tests/unit/aiplatform/test_training_jobs.py

Updated two tests:
* Added `google_auth_mock` to `test_explain_saved_model*` so those tests can run when `GOOGLE_APPLICATION_CREDENTIALS` is not set
* Added `skipif` to `test_training_jobs` to skip tests when `sys.executable` is not set

chore: updates so tests can run in different environments

---

google/cloud/aiplatform/models.py
tests/unit/aiplatform/test_endpoints.py

Fixes endpoint update method so it returns the resource and not an LRO.
Fixes b/235084784 🦕

fix: change endpoint update method to return resource

---

google/cloud/aiplatform/datasets/dataset.py
tests/system/aiplatform/test_dataset.py
tests/unit/aiplatform/test_datasets.py

feat: support dataset update

---

google/cloud/aiplatform/jobs.py
google/cloud/aiplatform/training_jobs.py
tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
tests/unit/aiplatform/test_automl_image_training_jobs.py
tests/unit/aiplatform/test_automl_tabular_training_jobs.py
tests/unit/aiplatform/test_automl_text_training_jobs.py
tests/unit/aiplatform/test_automl_video_training_jobs.py
tests/unit/aiplatform/test_hyperparameter_tuning_job.py
tests/unit/aiplatform/test_jobs.py
tests/unit/aiplatform/test_training_jobs.py

So that our unit test suite runs faster, I've made global variables for job polling times in `jobs.py` and `training_jobs.py`. Then I've patched these in our job tests.

chore: performance improvements to unit tests

---

tests/system/aiplatform/test_model_monitoring.py

chore: system test for model monitoring

---

setup.py

Reverting googleapis/python-aiplatform#1444 since it caused system tests to fail

chore: Revert "chore: Support bigquery 3.x"

---

google/cloud/aiplatform/constants/pipeline.py
google/cloud/aiplatform/pipeline_jobs.py

Internal cleanup so any future modules that reference pipeline job constants don't need to import from `pipeline_jobs`. This will prevent circular import errors.

chore: move pipeline constants to constants file

---

google/cloud/aiplatform/pipeline_jobs.py
tests/system/aiplatform/test_experiments.py
tests/unit/aiplatform/test_pipeline_jobs.py

Added a `get_associated_experiment` method to `PipelineJob` to return the Experiment associated with the provided pipeline job.

feat: add get_associated_experiment method to pipeline_jobs

---

tests/unit/aiplatform/test_explain_lit.py

Updated mocks for `notebook.LitWidget` so they run correctly in different environments. Applies to the 3 tests that use `widget_render_mock`.

chore: update lit explain mocks

---

tests/unit/aiplatform/test_training_utils.py

Added `skipif` to 2 tests so this test file runs when `sys.executable` is not available.
Fixes b/237443185 🦕

chore: add skipif to tests that rely on sys.executable

---

.kokoro/test-samples-impl.sh

This PR is to address a test failure issue with Kokoro test infra. 
Changing the python version used to  `python3` instead of `python3.6`

ci: Change install nox command to use the default python.

---

google/cloud/aiplatform/constants/base.py

Add Vertex Tables Q2 region in the SUPPORTED_REGIONS set to enable the SDK. The implementation of this region is complete and the change is required for E2E tests.

feat: Add support for Vertex Tables Q2 regions

---

tests/system/aiplatform/test_dataset.py

Referenced a smaller text extraction dataset file for the `test_get_new_dataset_and_import` system test to avoid timeouts.
Fixes https://github.com/googleapis/python-aiplatform/issues/1484 🦕

chore: use smaller data file in dataset import test

---

tests/system/aiplatform/test_matching_engine_index.py

Matching Engine rolled out ID validation for `deployed_index_id`, which caused our system test to fail since the ID had dashes.
Fixes https://github.com/googleapis/python-aiplatform/issues/1517 🦕

chore: update index id in matching engine system test

---

google/cloud/aiplatform/pipeline_jobs.py

fix: Fixed getting the output GCS bucket in PipelineJob.submit

---

.kokoro/continuous/system.cfg

Our last 2 system test runs timed out because they went over the 5 hour timeout we had. Increasing to 6 hours.

chore: increase system test timeout to 6 hours

---

.kokoro/continuous/system.cfg

Temporary fix for https://github.com/googleapis/python-aiplatform/issues/1551 while we try to decrease total execution time for Model Monitoring system tests.

chore: increase kokoro VM timeout for system tests

---

google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/datasets/image_dataset.py
google/cloud/aiplatform/datasets/tabular_dataset.py
google/cloud/aiplatform/datasets/text_dataset.py
google/cloud/aiplatform/datasets/time_series_dataset.py
google/cloud/aiplatform/datasets/video_dataset.py

Minor docstring update. s/model/dataset/g

fix: Correct docstring in Dataset classes

---

tests/system/aiplatform/test_model_monitoring.py

chore: add manual resource removal to model monitoring system tests

---

samples/model-builder/experiment_tracking/log_pipeline_job_sample.py

The sample used on [this page](https://cloud.google.com/vertex-ai/docs/experiments/add-pipelinerun-experiment#associate-pipeline-run-with-experiment-run) had the wrong param names. 
Fixes b/240621638 🦕

chore: update expeirments sample to use correct param names

---

google/cloud/aiplatform/base.py
tests/unit/aiplatform/test_datasets.py
tests/unit/aiplatform/test_featurestores.py
tests/unit/aiplatform/test_matching_engine_index.py
tests/unit/aiplatform/test_matching_engine_index_endpoint.py
tests/unit/aiplatform/test_models.py
tests/unit/aiplatform/test_pipeline_jobs.py
tests/unit/aiplatform/test_tensorboard.py

fix: Study.list() method

---

samples/model-builder/conftest.py
samples/model-builder/model_registry/assign_aliases_model_version_sample.py
samples/model-builder/model_registry/assign_aliases_model_version_sample_test.py
samples/model-builder/model_registry/create_aliased_model_sample.py
samples/model-builder/model_registry/create_aliased_model_sample_test.py
samples/model-builder/model_registry/create_default_model_sample.py
samples/model-builder/model_registry/create_default_model_sample_test.py
samples/model-builder/model_registry/create_model_registry_sample.py
samples/model-builder/model_registry/create_model_registry_sample_test.py
samples/model-builder/model_registry/delete_aliases_model_version_sample.py
samples/model-builder/model_registry/delete_aliases_model_version_sample_test.py
samples/model-builder/model_registry/delete_model_sample.py
samples/model-builder/model_registry/delete_model_sample_test.py
samples/model-builder/model_registry/delete_model_version_sample.py
samples/model-builder/model_registry/delete_model_version_sample_test.py
samples/model-builder/model_registry/get_model_version_info_sample.py
samples/model-builder/model_registry/get_model_version_info_sample_test.py
samples/model-builder/model_registry/get_registered_model_version_sample.py
samples/model-builder/model_registry/get_registered_model_version_sample_test.py
samples/model-builder/model_registry/list_model_versions_with_model_registry_sample.py
samples/model-builder/model_registry/list_model_versions_with_model_registry_sample_test.py
samples/model-builder/model_registry/upload_new_aliased_model_version_sample.py
samples/model-builder/model_registry/upload_new_aliased_model_version_sample_test.py
samples/model-builder/model_registry/upload_new_default_model_version_sample.py
samples/model-builder/model_registry/upload_new_default_model_version_sample_test.py
samples/model-builder/model_registry/upload_new_model_version_using_custom_training_pipeline_sample.py
samples/model-builder/model_registry/upload_new_model_version_using_custom_training_pipeline_test.py
samples/model-builder/test_constants.py

docs(samples): add Model Registry samples to Vertex AI Python SDK

---

samples/model-builder/experiment_tracking/log_metrics_sample.py
samples/model-builder/experiment_tracking/log_params_sample.py

Use correct param names (`experiment` and `run`) in experiments samples. See [here](https://github.com/googleapis/python-aiplatform/blob/34bbd0abbaf29e644ed7703b3251f1de65bf5a86/google/cloud/aiplatform/initializer.py#L60) and [here](https://github.com/googleapis/python-aiplatform/blob/34bbd0abbaf29e644ed7703b3251f1de65bf5a86/google/cloud/aiplatform/metadata/metadata.py#L245).
Fixes #1605 🦕

chore: fix param names in experiments samples

---

google/cloud/aiplatform/metadata/resource.py
google/cloud/aiplatform/metadata/schema/utils.py
tests/unit/aiplatform/test_metadata_resources.py
tests/unit/aiplatform/test_metadata_schema.py

feat: Support ResourceName with Version.

---

tests/system/aiplatform/test_model_monitoring.py

System test was erroring out due to missing `aiplatform.init` in refactored model monitoring system test. As a result, kokoro picked a random test project for this script to run in. 

chore: add aiplatform.init back to model monitoring system tests

---

tests/system/aiplatform/e2e_base.py
tests/system/aiplatform/test_e2e_tabular.py

Removed AutoML model training from `tests/system/aiplatform/test_e2e_tabular`. This update creates the training job, checks the state is `RUNNING`, and then cancels it. 
The prediction test references a permanent tabular endpoint resource I set up. Based on the time improvements we get from this, we can consider doing the same for other tests that train AutoML models.
Fixes b/244325057 🦕

chore: e2e tabular system test improvement

---

tests/system/aiplatform/test_model_interactions.py

This fixes the test failures in `test_model_interactions.py`. Note to self: `aiplatform.init` needs to be called at the beginning of every system test, otherwise kokoro randomly assigns a project number to the test suite. 

chore: add aiplatform.init to test_model_interactions.py

---

google/cloud/aiplatform/metadata/experiment_run_resource.py

docs: ExperimentRun docstring and end_run kwarg

---

google/cloud/aiplatform/metadata/constants.py
google/cloud/aiplatform/pipeline_jobs.py
tests/unit/aiplatform/test_metadata.py

Add new Model Evaluation metric schema types to `get_experiment_df`. With this addition, calling `get_experiment_df` will return metrics produced by Model Evaluation pipelines.

feat: add eval metrics types to get_experiment_df

---

CONTRIBUTING.rst
google/cloud/aiplatform/vizier/pyvizier/__init__.py
noxfile.py
owlbot.py
setup.py

Hey @parthea, I think we're ready to support Python version 3.10 (TensorFlow now supports Python 3.10). Is there more to do for 3.10 support other than adding the extra line to `setup.py` (I'm assuming this change will automatically update the related files) or will I need to manually add to `CONTRIBUTING.rst`, `noxfile.py`, and `owlbot.py` (according to https://github.com/googleapis/python-aiplatform/pull/831)?
Thanks,
Nishant

feat: adding Python 3.10 support + updating google-vizier version

---

google/cloud/aiplatform/constants/pipeline.py
google/cloud/aiplatform/pipeline_jobs.py
google/cloud/aiplatform/utils/yaml_utils.py
tests/unit/aiplatform/test_pipeline_jobs.py
tests/unit/aiplatform/test_utils.py

First-party pipelines are not yet available in AR, meaning other than using a local file, the only way to access a first-party pipeline is using its GitHub URI. Since support was added for AR URIs, it is not much more effort to support general HTTPS URIs.
Fixes b/247878583 🦕

feat: add support for HTTPS URI pipeline templates

---

google/cloud/aiplatform/datasets/dataset.py
google/cloud/aiplatform/featurestore/entity_type.py
google/cloud/aiplatform/training_jobs.py

docs: fix typos

---

google/cloud/aiplatform/base.py
google/cloud/aiplatform/utils/__init__.py
tests/unit/aiplatform/test_featurestores.py
tests/unit/aiplatform/test_utils.py

For nested resources like EntityType (Featurestore -> EntityType -> Feature), the project/location needs to be extracted from the full resource name and passed into the client constructor. Adding check to see if parent exists and utility method to extract project and location from the parent resource name.
Fixes [b/249363374](https://b.corp.google.com/issues/249363374) and https://github.com/googleapis/python-aiplatform/issues/1684 🦕

fix: project/location parsing for nested resources

---

.github/CODEOWNERS

Adding SDK eng team to default owners of codebase. Files without explicit ownership in the repo will require all three parties to approve.

chore: adding SDK team to CODEOWNERS

---

google/cloud/aiplatform/utils/yaml_utils.py
tests/unit/aiplatform/test_utils.py

When downloading compiled KFP pipelines over HTTPS, we only need to pass a bearer token when we need to authenticate for services like Artifact Registry. We may get unexpected behavior passing this token in all HTTPS requests, which is the current behavior.
Fixes b/251143831 🦕

fix: PipelineJob should only pass bearer tokens for AR URIs

---

README.rst

Remove trailing slash from resource name in Model Eval section of readme

chore: fix typo in readme
